CREATE TABLE IF NOT EXISTS `%s` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `map_id` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  `player_id` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  `kills` MEDIUMINT UNSIGNED NOT NULL DEFAULT '0',
  `deaths` MEDIUMINT UNSIGNED NOT NULL DEFAULT '0',
  `teamkills` MEDIUMINT UNSIGNED NOT NULL DEFAULT '0',
  `teamdeaths` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  `suicides` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  `rounds` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `map_id` (`map_id`),
  KEY `player_id` (`player_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;