CREATE TABLE IF NOT EXISTS `%s` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `action_id` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `player_id` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  `count` MEDIUMINT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `action_id` (`action_id`),
  KEY `player_id` (`player_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;