CREATE TABLE IF NOT EXISTS `%s` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL DEFAULT '',
  `kills` MEDIUMINT UNSIGNED NOT NULL DEFAULT '0',
  `teamkills` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  `suicides` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;